stages:
  - build
  - publish

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  VERSION: "${CI_COMMIT_TAG#v}"

before_script:
  - python -m pip install --upgrade pip
  - pip install build twine toml

build:
  stage: build
  script:
    - python -m build
  artifacts:
    paths:
      - dist/

build-publish:
  stage: build
  script:
    - echo "Setting version to $VERSION"
    - python scripts/set_version.py $VERSION
    - python -m build
  artifacts:
    paths:
      - dist/
  rules:
    - if: $CI_COMMIT_TAG
      when: always

publish:
  stage: publish
  script:
    - twine upload dist/*
  only:
    - tags
 